### ISSUE TITLE
'D001 found declareProtected' in object

### ISSUE THREAD

**Issue by idgserpro** [gforcada/flake8-deprecated#10]
I have the code:

``` python
security.declareProtected(ManageUsers, 'manage_edit_tibco_form')
manage_edit_tibco_form = PageTemplateFile(
    'browser/edit_plugin.zpt', globals(),
    __name__='manage_edit_tibco_form')
```

I get the error:

``` bash
./bin/code-analysis
CSS Lint.............................[ OK ] in 0.007s
JSHint...............................[ OK ] in 0.007s
Check clean lines....................[ OK ] in 0.030s
Flake8..........................[ FAILURE ] in 0.858s
/home/user/sites/certificadoidg105/zeocluster/src/serpro.pas.tibco/serpro/pas/tibco/plugin.py:45:14: D001 found declareProtected( replace it with AccessControl.ClassSecurityInfo.protected
The command "bin/code-analysis" exited with 1 in 0.868s.
```

But `manage_edit_tibco_form` is an object and not a method. How fix it?

**Comment by gforcada** [comment]
Thanks for the report, but I'm really not sure how to fix that, maybe asking at AccessControl github repo? https://github.com/zopefoundation/AccessControl that deprecation comes from there, so they may have something in place already.

**Comment by idgserpro** [comment]
@gforcada I didn't found in AccessControl where it says that declareProtected is deprecated.

See [this comment](https://github.com/gforcada/flake8-deprecated/commit/403593949a2fc0bc1c79d2ca777e0125d27feb3a#commitcomment-15716858). @jensens can you help?

Perhaps a way to fix it would be throw an error in `security.declareProtected(ManageUsers, 'name')`, only if there is `def name(` in the file.

**Comment by jensens** [comment]
@idgserpro IIRC it simply that this way of declaring wont work in Python 3. So we're on a good track if we use decorators.

**Comment by idgserpro** [comment]
@jensens I agree that it is better to use decorator. But in the case of this issue, `manage_edit_tibco_form` is a variable and not a method. We can not use decorator in variables. How to proceed?

**Comment by jensens** [comment]
since this variables are in fact also callables, it should be possible to pass them as a parameter of the decorator. Looking into https://github.com/zopefoundation/AccessControl/blob/master/src/AccessControl/SecurityInfo.py#L113 it looks like It works like so (off-head/untested):

```
class SomeThing(object):

    security = ClassSecurityInfo()

    # private and public (w/o parameters)
    manage_something_private = security.private(manage_something_private)
    manage_something_public = security.public(manage_something_public)

    # protected works a bit different:
    manage_something_protected = security.protected(SOME_PERMISSION)(manage_something_public)
```

**Comment by idgserpro** [comment]
@jensens this worked. Thank you!
