### ISSUE TITLE
assert_ also matches assert_called_once_with()

### ISSUE THREAD

**Issue by The-Compiler** [gforcada/flake8-deprecated#3]
When using a `unittest.mock`, there are certain `assert_*` methods to be called, e.g. `m.assert_called_once_with()`.

Those get flagged wrongly:

```
D001 found assert_ replace it with assertTrue
```

I think this is a general problem, i.e. those matchers should only match if the full function name matches.

**Comment by gforcada** [comment]
Hi @The-Compiler sorry I didn't see this issue.

We could just extend it to be `assert_(`. What do you think?

**Comment by The-Compiler** [comment]
sounds good to me - probably for the other matchers as well though?

**Comment by gforcada** [comment]
@The-Compiler sure, would you mind creating a pull request for it?

**Comment by The-Compiler** [comment]
I'm afraid I'm involved in [too much stuff](https://github.com/The-Compiler) and thus too busy at the moment - sorry!

(I'm also not using `flake8-deprecated` as I'm not using any of the libraries it checks things for - just gave it a quick try and thought I'd report this :wink:)

**Comment by gforcada** [comment]
@The-Compiler sure no problem, I will try to get around doing it myself-

Thanks for reporting!

**Comment by gforcada** [comment]
Fixed on https://github.com/gforcada/flake8-deprecated/commit/e4f0071245a63049486a8557716207dad7b2cb1b

**Comment by gforcada** [comment]
@The-Compiler I released 1.0, give it a try :)

**Comment by The-Compiler** [comment]
Works like a charm, thanks!
