### ISSUE TITLE
Wrongly warns about Grok stuff

### ISSUE THREAD

**Issue by hvelarde** [gforcada/flake8-deprecated#9]
I'm getting a warning like this:

``` console
src/sc/embedder/content/embedder.py:151:10: D001 found implements( replace it with zope.interface.implementer
```

over code like this:

``` python
from five import grok
...

class Embedder(dexterity.Item):
    ...
    grok.implements(IEmbedder)
    ...
```

we need to handle this on a different way.

**Comment by gforcada** [comment]
Well for this specific case we could easily prefix a space and we are done :-)

**Comment by gforcada** [comment]
Grok is more or less death, I guess, and so far interest has been shown... so closing for now.
